source ~/.config/nvim/vim-plug/plugins.vim
source ~/.config/nvim/general/settings.vim
source ~/.config/nvim/keys/mappings.vim
source ~/.config/nvim/themes/onedark.vim
source ~/.config/nvim/themes/airline.vim
"source ~/.config/nvim/plug-config/coc.vim
source ~/.config/nvim/plug-config/rnvimr.vim
source ~/.config/nvim/plug-config/fzf.vim
luafile ~/.config/nvim/lua/plugins/plug-colorizer.lua
source ~/.config/nvim/plug-config/start-screen.vim
source ~/.config/nvim/plug-config/signify.vim
source ~/.config/nvim/plug-config/sneak.vim
source ~/.config/nvim/keys/which-key.vim
source ~/.config/nvim/plug-config/floaterm.vim
luafile ~/.config/nvim/lua/plugins/compe-config.lua
source ~/.config/nvim/plug-config/vim-vsnip.vim
" LSP: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md
source ~/.config/nvim/plug-config/lsp-config.vim
luafile ~/.config/nvim/lua/lsp/typescript-ls.lua
luafile ~/.config/nvim/lua/lsp/html-ls.lua
